name: Team11 Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # এই স্টেপটা জোর করে তোর সব ফাইলে ডাউনলোডের লিঙ্ক ঢুকিয়ে দেবে
      - name: Force Inject Repositories
        run: |
          find . -name "*.gradle" -type f -exec sed -i 's|repositories *{|repositories { \n        jcenter() \n        maven { url "https://jitpack.io" }|g' {} +

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Team11 APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload Team11 APK
        uses: actions/upload-artifact@v4
        with:
          name: Team11-App
          path: app/build/outputs/apk/debug/app-debug.apk
